- name: catalouge
  hosts: catalouge
  become: yes
  tasks:
  - name: catalouge removing old version 
    ansible.builtin.shell: dnf module disable nodejs -y;dnf module enable nodejs:18 -y
  - name: installing new package
    ansible.builtin.package:
     name: nodejs
     state: present
  

  
