- name: installing mysql
  hosts: 
  become: yes
  tasks:
  - name: install sql
    ansible.builtin.command: dnf module disable mysql -y
  
  - name: Copy a "sudoers" file on the remote machine for editing
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo
      remote_src: yes

  - name: installing server
    ansible.builtin.package:
     name: mysql-community-server
     state: present
    
  - name: start and enable
    ansible.builtin.service:
     name: mysqld
     enabled: yes
     state: started

  - name: install sql
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1