- name: catalouge
  hosts: user
  become: yes
  tasks:
    - name: catalouge removing old version
      ansible.builtin.shell: dnf module disable nodejs -y;dnf module enable nodejs:18 -y

    - name: installing new package
      ansible.builtin.dnf:
        name: nodejs
        state: present
        
    - name: Add the user 'roboshop' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: roboshop

    - name: Recursively remove directory
      ansible.builtin.file:
       path: /app
       state: absent

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app
        state: directory # here state ,directory needs to be mentioned other wiese it will take as file
        

    - name: Download the application code to created app directory.
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/user.zip
        dest: /tmp

    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes

    - name: installing npm
      ansible.builtin.shell: npm install
      args:
        chdir: /app

    - name: copy
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: Restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: copy
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: installing pks
      ansible.builtin.package:
        name: mongodb-org-shell
        state: present

    - name: get the categories count
      ansible.builtin.command: mongo --host 172.31.82.179 --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
      register: user_count

    # - name: print the count
    #   ansible.builtin.debug:
    #     msg: "product count: {{product_count}}"

    - name: load user data
      ansible.builtin.command: mongo --host 172.31.82.179 < /app/schema/user.js
      when: product_count.stdout == "0" # keep double quotes

    - name: Start service mongodb, if not started
      ansible.builtin.service:
        name: user
        state: restarted
        enabled: yes
